name: Deploy on Release Published

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy_to_powershellgallery:
    runs-on: ubuntu-latest
    environment: powershellgallery
    steps:
      - uses: actions/checkout@v3
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT

      - name: deploy_ps1
        shell: pwsh
        run: | 
          $ref = "${{github.event.ref}}"

          If ([string]::IsNullOrEmpty($ref)) {
            # Release published trigger
            $tag = "${{github.event.release.tag_name}}"
            $releaseName = "${{github.event.release.name}}"
            write-host -message "Release [$releaseName] on tag [$tag]"
          } else {
            # Read Tag o Branch name
            $tag = $ref.Split('/')[2]
            write-host "workflow_dispatch triggered on ref leaf [$tag]"
          }

          If([string]::IsNullorwhitespace($tag)) {
            # Tag name is empty, exit
            write-error "Tag name is empty"
            exit 1
          }

          ./deploy.ps1 -VersionTag $tag -NugetApiKey "${{secrets.NUGETAPIKEY}}"

